### ISSUE TITLE
Sessions need way to check auth

### ISSUE THREAD

**Issue by ebramanti** [lmucs/cher-ami#12]
We need to be able to `GET` request to the `/sessions` endpoint to see if the session even exists. If not, we should redirect to our LoginView so that the user can sign in.

We simply need to return true/false if the session exists. An [example](http://backbonetutorials.com/cross-domain-sessions/) I found said this about the three different type of requests made to our `/sessions` endpoint:
- `POST /session` - Login - Sets the session username and returns a token for the user to use
- `DELETE /session` - Logout - Destroys the session and regenerates a new token if the user wants to re-login
- `GET /session` - Checks Auth - Simply returns if auth is true or false, if true then also returns some session details

**Comment by rtoal** [comment]
I disagree.  What is the point of checking for the existence of a session?  It serves ZERO purpose and I see it as a huge negative.  Probably a security hole; someone might be able to exploit it for something.

Closing because this is not appropriate.  If there are some session details you wish to expose through the API and you can convince me that we can't live without them. then reopen.

**Comment by ebramanti** [comment]
I'm confused... Every example I've seen with Backbone/Marionette sessions for login/logout and persisting a user's login state is done at app load with a `GET` request to a sessions route. The example I was reading was this:

https://github.com/DanialK/advanced-security-in-backbone

EDIT: Even more specifically, [this](https://github.com/DanialK/advanced-security-in-backbone/blob/master/public/scripts/Session.js#L107-L125).

**Comment by rtoal** [comment]
But how, how, how, is it used, and WHY do they have such a thing.

If Backbone REQUIRES it, put it in.  Seems pathetic and awful to pollute the API with. :(

In every API I've seen, you NEVER, EVER "get" a session from the server.  You send a request with your token.  If the token is invalid or expired, the call you made gives a 401.

"Checking to see if a token is valid" by a GET request is IMO a security risk and it is a stupid race condition if you get something and then send it back because it might have expired in between the first call (the GET) and the second (which is the use).

Now it may very well be that Backbone, because it does so much magic, needs to have the endpoint exposed.  If so, so be it, because Backbone is cool.  But holy crap that is a DISGUSTING endpoint to require.  End of rant!  Feel free to reopen!

I need to take some deep breaths.  Then I need to reread the example.  What is probably happening is that a backbone session is different from an auth token.  Hopefully there is SOME logical explanation like that, because you should never grab an in-use token with a GET.  May this all be a misunderstanding. ;-)

**Comment by AuthorOfTheSurf** [comment]
I think Ed's phrasing was a bit off in the initial part of the issue.

The point of the `GET /sessions` endpoint is for comparison, not to discover whether a session exists for some user. The client puts their current auth token in the header: `Authorization: xsD2$sdsa@llsks` and then preforms the request to verify if they are still logged in.

The request responds in one of two ways:
If the Authorization token matches that of the user, return true. If there is no match, or the session is expired or doesn't exist at all, return false.

The purpose of the endpoint is so that the client can determine if it needs to re-prompt the user to log in again. I understand that authorization supposed to be apart of select routes and not an individually verifiable thing, however the way this is set up, no information is leaked that couldn't be leaked by a slightly different request like `GET circles/:user` which requires the same auth token and just the user's handle extra.

An alternative would be to have the clients execute a `GET user/:handle` on start-up to get profile data for their profile pages. If the request fails, then take the user to a login page instead of their profile with a polite request to sign-in again.

I think what I just proposed is more rest-ful and more similar to how auth should work. It should be a state that determines where a user can go. So instead of asking questions about user state the question should be "Can I view this users (my own) profile page?", yes-OK, no-taken to login page. Different resource based on state without having to explicitly add the endpoint.

Or should a `failed auth -> login page` action happen every time a need-authentication route fails to authenticate?

EDIT: Backbone does not require the route. And I understand the very real race condition that could occur, essentially nullifying any purpose the route would have in the first place.

**Comment by rtoal** [comment]
Oh I see.... It is easy to see why if POST /sessions would create a session and DELETE /sessions would delete one, the GET /sessions would seem to ... get a session.  It seems like you are saying it doesn't, that instead it just returns true or false, but again that looks like a race condition to me.

But my question would be why doesn't his check just get done on every normal request?  WHY is a separate request needed?

The way things normally work is that after the token expires a response with a 401 comes back.  The client can do whatever it wants with the 401.  It can redirect to a login page (and probably will).  But the thing I am still missing is why would the API be exposing a vanilla endpoint that says "am i still logged in?"  Is the point just that the client can poll (long poll) the validity of the session so that the login view pops up during inactivity periods, thus keeping the user from coming back to the app, trying something out, and saying "Damn, grrrrr, now I wasted time doing that"?

If so, I retract my objections.  Pinging or polling login status is fine.  Reopening,

Where did you learn to write so well, @AuthorOfTheSurf?

**Comment by AuthorOfTheSurf** [comment]
Thank you for the complement, distinguishing the difference between things is important to me.

You are correct, the endpoint is purely a ping, not to get any session-related info outside of the comparison. A ping that would be hit when the app is opened to determine if the user should be told to login before doing anything else. This check is done on all routes that require authorization but is not available outside of that. So a client can only determine if they are authorized by requesting such a route.

This brings up the fix, either adding an endpoint that may be vulnerable to a race condition, or making a certain request the standard "first request" that a client should run.

I have spent the past 30 mins discussing the options with @jadengore and we have resolved to make it a request to `UserHomePage`, a route that doesn't really exist yet (could be `/profile/:user`). This action is very similar to other web applications, where you will be taken to your home page if you are logged in or some landing page if you are not. Web and mobile should have a place to store the `last handle that was logged in` so that this request can be made.

**Comment by rtoal** [comment]
Oh, please be careful, don't mix up the app with the API.   "UserHomePage" is not an API endpoint.  The API should be agnostic to clients.  Don't make the API return "pages" or HTML or anything like that.

Decisions like whether the app should check for login when the app opens are decisions for each individual client to make.  You shouldn't really be worrying about this.  YOU are not writing a webapp, you are making an API that can be hit by webapps, native apps, or even a commandline script written in C or Python.  Please don't worry about app (client) behavior. I think you sort of understand this but I'm not 100% clear.

You know if a client really wanted to know if it was logged in, via a ping, it could just as well issue a HEAD request to /users/{id} or any authenticated GET endpoint and if it doesn't get a 401 it's good.

I still don't like GET /sessions.  It just seems so wrong.  Let clients figure it out.  Not your job.  I'm glad you are trying to help them but let's keep the database layer, the service layer (API), and the clients all separate.  Maybe you are, but the word "UserHomePage" kind of freaked me out.

**Comment by AuthorOfTheSurf** [comment]
A bunch of this came up because @jadengore is currently working on the web app. So our conversations were related to that and it's implementation. `UserHomePage` is not an endpoint, it's more the set of endpoints that a client will hit to build their homepage view. This may turn out to be a HEAD request as you suggested.

I agree that we were designing this with a bit too much client in-mind, and there are certainly a number of ways a client could do this. To put it as you said, it is up to the client with how they want to design their webapp. It is up to API to provide the resources with the correct checks.

There will be no `GET /sessions` route added. Closing since nothing really needs to be added to the API to solve this issue.
